### ISSUE TITLE
Publish Vagrant box

### ISSUE THREAD

**Issue by jugglinmike** [bocoup-education/command-the-command-line#10]
Ideally, students should not have to download git and clone the repository to
participate in the exercises. By publishing the built Vagrant box, we can
instruct students to download a single `Vagrantfile` and run `vagrant up`.

**Comment by tkellen** [comment]
This is fairly closely related to https://github.com/bocoup/infrastructure/issues/236. If you decide to move on this I'd love to talk it through!

**Comment by tkellen** [comment]
This was resolved in https://github.com/bocoup/infrastructure/pull/257

**Comment by jugglinmike** [comment]
https://github.com/bocoup/infrastructure/pull/257 implemented the infrastructure necessary to resolve this. However, the Vagrant box I created has a number of problems and consequently it is not yet documented. I'd like to leave this issue as "open" until that is all cleared up.

**Comment by tkellen** [comment]
Roger that. Sorry for the premature close @jugglinmike!

**Comment by jugglinmike** [comment]
Implemented in f677b3fdaae697567b7c247f02fff6f22c038803 and documented in ce6f5e55f1b97c64d6c7e44cb9c7785f5e4da777. Box now available at http://boxes.bocoup.com/command-the-command-line.box

Thanks for your help, @tkellen!
