### ISSUE TITLE
User name in virtual machine

### ISSUE THREAD

**Issue by jugglinmike** [bocoup-education/command-the-command-line#22]
Initially, we built the virtual machine to [define a user named
"speaker"](https://github.com/bocoup-education/command-the-command-line/blob/2dac0729a129ae0e9c6ba572639e87e264f719f8/src/environment/provision.sh#L9)
(though in the process of re-branding from "Speaking \*nix" to "Command the
Command Line", I'm thinking of changing this to "speaker".). This was to be the
account used by participants in this workshop. I was afraid that the default
"vagrant" user might suggest some non-existent connection between the Vagrant
project and the environment itself. This confusion seems less likely with a
user name that is clearly customized for the course.

...but as I'm troubleshooting some permissions-related issues, I'm having
second thoughts. Given that [Vagrant is itself a formal topic for the
course](https://bocoup-education.github.io/command-the-command-line/vagrant/),
it might actually be better for participants to get experience with a more
stock configuration.

@tkellen @gnarf @cowboy @mattsurabian @brianloveswords @jennschiffer @reconbot I just
know you will have opinions on this. Mind sharing?

**Comment by gnarf** [comment]
Less custom config = better, and the `vagrant` user makes sense and kind of reminds you you're on the VM.

I think that `speaker` is likely to make people think they hacked your account mike ;)

I think just using `vagrant` would be fine

**Comment by tkellen** [comment]
:+1: to the stock configuration.

**Comment by cowboy** [comment]
> 👍 to the stock configuration.

👍 to this comment.

**Comment by jugglinmike** [comment]
Thanks for the input, folks! I've implemented your suggestion via f77574fa6346a3f40773e50b3a0f0f29cd292626. Now closing :)
